var GAME_LEVELS = [

	[" x                  x ",
	 " x @                x ",
	 " x                  x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x    hbbbbbbbbbbbbbn ",
	 " x    v             x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbbbbbg    x ",
	 " x             v    x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x   hbbbbbbbbbbbbbbn ",
	 " x   v              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                + x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x              ltttn ",
	 " x                  x "],
	[" mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                @ x ",
	 " x              ltttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbg   hbbbbbbbbn ",
	 " x         v        x ",
	 " x                  x ",
	 " x     ltj          x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbbg   hbbbn ",
	 " x              v   x ",
	 " x                  x ",
	 " x                  x ",
	 " x         i        x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbg  hbbbbbbbbbbn ",
	 " x       v          x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mg                 x ",
	 " xbg                x ",
	 " xbbg               x ",
	 " xbbbg        ltj   x ",
	 " xbbbbg             x ",
	 " xbbbbbg            x ",
	 " xbbbbbbg      d    x ",
	 " xbbbbbbbg          x ",
	 " xbbbbbbbbg         x ",
	 " xbbbbbbbbbg        x ",
	 " xbbbbbbbbbbg       x ",
	 " xbbbbbbbbbbbg      x ",
	 " xbbbbbbbbbbbg      h ",
	 " xbbbbbbbbbbg      hn ",
	 " x          v     hbx ",
	 " x               hbbx ",
	 " x              hbbbx ",
	 " x +           hbbbbx ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mtttj              x "],
	[" mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x @      f         x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbg  hbbbg  hbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " x                  x ",
	 " x  f           f   x ",
	 " x                  x ",
	 " x          f       x ",
	 " x     hbg          x ",
	 " x     v            x ",
	 " x                  x ",
	 " x  d     hbbg d    x ",
	 " x           v      x ",
	 " x                  x ",
	 " x hbbbbbbbbbbbg  hbx ",
	 " x v    i      v    x ",
	 " x                  x ",
	 " x                  x ",
	 " x          i       x ",
	 " xbbg  hbbbbbbbbbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " xd                 x ",
	 " x                  x ",
	 " x                  x ",
	 " x d                x ",
	 " x                  x ",
	 " x                  x ",
	 " x  d               x ",
	 " x                  x ",
	 " x                  x ",
	 " x   d              x ",
	 " x                  x ",
	 " x                  x ",
	 " x    d             x ",
	 " x                  x ",
	 " x                  x ",
	 " x     d            x ",
	 " x                  x ",
	 " x                  x ",
	 " x      d           x ",
	 " x                  x ",
	 " x                  x ",
	 " x       d          x ",
	 " x                  x ",
	 " x                  x ",
	 " x        d         x ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " x        lxj       x ",
	 " x       d      lxj x ",
	 " x   lxj            x ",
	 " x          lxj     x ",
	 " x    lxj       i   x ",
	 " x          f       x ",
	 " x                  x ",
	 " x lxj   lxj   lxj  x ",
	 " x   i              x ",
	 " x                  x ",
	 " x   hbbbg hbbbg    x ",
	 " x   v     v        x ",
	 " x  d  d      d  d  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x          v       x ",
	 " x                  x ",
	 " x   v              x ",
	 " x             v    x ",
	 " x                  x ",
	 " x       v          x ",
	 " x                  x ",
	 " x                  x ",
	 " x d              d x ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x         +        x ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x +        i       x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xfffffffv   fffffffx ",
	 " xffffff       fffffx ",
	 " xfffff         ffffx ",
	 " xffff           fffx ",
	 " xfff          hbbbbx ",
	 " xff           hbbbbx ",
	 " xf            hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  hbbbbx ",
	 " xbbbbbbbbbbg  v    x ",
	 " xbbbbbbbbbbg       x ",
	 " xbbbbbbbbbbg       x ",
	 " x                  x ",
	 " x  f               x ",
	 " x                  x ",
	 " x     hbbbbbbbbbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " x      d   hbbbg   x ",
	 " x                  x ",
	 " x                  x ",
	 " x   hbbbg     d    x ",
	 " x                  x ",
	 " x       i          x ",
	 " x                  x ",
	 " x   d   hbbbg      x ",
	 " x                  x ",
	 " x                  x ",
	 " xbbbbg          d  x ",
	 " x                  x ",
	 " x                  x ",
	 " x           hbbbg  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x     i            x ",
	 " x     hbbbg    d   x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x    d        hbbbbx ",
	 " x                  x ",
	 " x                  x ",
	 " x  hbbbg           x ",
	 " x                  x ",
	 " x             lxxxxn ",
	 " x                  x ",
	 " x                  x ",
	 " x             lxj  x ",
	 " x lxj              x ",
	 " x    f         f   x ",
	 " x        lxj       x ",
	 " x       f          x ",
	 " x            lxj   x ",
	 " x   lxj            x ",
	 " x      f         f x ",
	 " x    f             x ",
	 " x         lxj      x ",
	 " xf             f   x ",
	 " x   lxj            x ",
	 " x            lxj   x ",
	 " x f                x ",
	 " x     lxj          x ",
	 " x          lxj     x ",
	 " x              f   x ",
	 " x     lxj      f   x ",
	 " x        f         x ",
	 " x            lxj   x ",
	 " x   lxj            x ",
	 " x f            f   x ",
	 " x              f   x ",
	 " x      lxj         x ",
	 " x   f      f       x ",
	 " x   f              x ",
	 " x             lxj  x ",
	 " x  lxj             x ",
	 " x                  x ",
	 " xtttttttj  ltttttttx ",
	 " xbbbbbbbg  hbbbbbbbx ",
	 " xbbbbbbg    hbbbbbbx ",
	 " xbbbbbgv    vhbbbbbx ",
	 " xbbbbgv      vhbbbbx ",
	 " xbbbgv        vhbbbx ",
	 " x   v          v   x ",
	 " x                  x ",
	 " x                  x ",
	 " x         @        x ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                + x ",
	 " x              ltttn ",
	 " x                  x ",
	 " x    d          d  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbg   hbbbbbbbbn ",
	 " x     v            x ",
	 " x                  x ",
	 " x    iltj d        x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbbg   hbbbn ",
	 " x              v   x ",
	 " x      d           x ",
	 " x                  x ",
	 " x         i        x ",
	 " x                d x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbg  hbbbbbbbbbbn ",
	 " x       v         fx ",
	 " x                f x ",
	 " x    d            fx ",
	 " x           d    f x ",
	 " x                 fx ",
	 " xf       i       f x ",
	 " xgf               fx ",
	 " xbgf             f x ",
	 " xbbgf       ltj   fx ",
	 " xbbbgf           f x ",
	 " xbbbbgf           fx ",
	 " xbbbbbgf         f x ",
	 " xbbbbbbgf         fx ",
	 " xbbbbbbbgf       f x ",
	 " xbbbbbbbbgf       fx ",
	 " xbbbbbbbbbgf     f x ",
	 " xbbbbbbbbbbgf     fx ",
	 " xbbbbbbbbbbgf    f x ",
	 " xbbbbbbbbbgf      fx ",
	 " x         v      fhx ",
	 " x               fhbx ",
	 " x              fhbbx ",
	 " x @           fhbbbx ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " x                  x ",
	 " x +                x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x    hbbbbbbbbbbbbbn ",
	 " x   d  d  d  d  d  x ",
	 " x    i     i       x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x      i     i     x ",
	 " mbbbbbbbbbbbbbg    x ",
	 " xd  d  d  d  d     x ",
	 " x     i     i      x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x   hbbbbbbbbbbbbbbn ",
	 " x   d  d  d  d  d  x ",
	 " x                  x ",
	 " x        i         x ",
	 " x                  x ",
	 " x                @ x ",
	 " mttttttttttttttttttn "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

