var GAME_LEVELS = [
	[" x                  x ",
	 " x @                x ",
	 " x                  x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x        f         x ",
	 " x                  x ",
	 " x             i    x ",
	 " x                  x ",
	 " x                  x ",
	 " x      hbbbbbbbbbbbn ",
	 " x      v           x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbg    d   x ",
	 " x         v        x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                + x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x              ltttn ",
	 " x                  x "],
	[" mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                @ x ",
	 " x              ltttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbb     bbbbbbbn ",
	 " x                  x ",
	 " x                  x ",
	 " x     ltj          x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbb    bbbbn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbb   bbbbbbbbbbn ",
	 " x        b         x ",
	 " x        b         x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mb                 x ",
	 " x b                x ",
	 " x  b               x ",
	 " x   b        ltj   x ",
	 " x    b             x ",
	 " x     b            x ",
	 " x      b           x ",
	 " x       b          x ",
	 " x        b         x ",
	 " x         b        x ",
	 " x          b       x ",
	 " x           b      x ",
	 " x           b      b ",
	 " mbbbbbbbbbbb      bn ",
	 " x                b x ",
	 " x               b  x ",
	 " x              b   x ",
	 " x +           b    x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mtttj              x "],
	[" mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x @                x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x         +        x ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x +                x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x         @        x ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " mttttttttttttttttttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                + x ",
	 " x              ltttn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x @                x ",
	 " mttttttttttttttttttn "],
	[" x                  x ",
	 " x                  x ",
	 " x +                x ",
	 " mtttj              x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x      bbbbbbbbbbbbn ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " mbbbbbbbbbb        x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                  x ",
	 " x                @ x ",
	 " mttttttttttttttttttn "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

